<?php
session_start();
require_once '../config/config.php'; // Database connection

// Placeholder for admin authentication
if (!isset($_SESSION['username'])) { // This should be a proper admin role check
    echo "<p style='color:red;'><strong>Note:</strong> Admin authentication is not yet implemented. This page should be protected.</p>";
}

$message = $_GET['message'] ?? ''; // For displaying messages from GET params
$action_message = ''; // For messages generated by actions on this page load

// Handle Delete Action
if (isset($_GET['action']) && $_GET['action'] === 'delete' && isset($_GET['id'])) {
    $user_id_to_delete = $_GET['id'];

    // Prevent admin from deleting their own account (assuming 'user_id' is stored in session upon login)
    // If 'user_id' is not in session, this check will be skipped.
    // A more robust solution would ensure 'user_id' is reliably set for logged-in admins.
    if (isset($_SESSION['user_id']) && $user_id_to_delete == $_SESSION['user_id']) {
        $action_message = "Error: You cannot delete your own account.";
    } else {
        try {
            // ON DELETE CASCADE for comments, watch_history, favorites will handle related data.
            $stmt = $conn->prepare("DELETE FROM users WHERE id = :id");
            $stmt->bindParam(':id', $user_id_to_delete, PDO::PARAM_INT);
            $stmt->execute();

            if ($stmt->rowCount() > 0) {
                $action_message = "User (ID: $user_id_to_delete) deleted successfully!";
            } else {
                $action_message = "Error: User (ID: $user_id_to_delete) not found or already deleted.";
            }
        } catch (PDOException $e) {
            $action_message = "Error deleting user (ID: $user_id_to_delete): " . $e->getMessage();
        }
    }
    // Redirect to clean the URL and show the message
    header("Location: manage_users.php?message=" . urlencode($action_message));
    exit;
}


// Fetch all users for listing
$users_list = [];
try {
    $stmt_users = $conn->query("SELECT id, username, email, created_at FROM users ORDER BY username ASC");
    if ($stmt_users) $users_list = $stmt_users->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    $current_error_message = " Error fetching users list: " . $e->getMessage();
    if(!empty($message)) {
        $message .= urldecode($current_error_message); 
    } else {
        $message = $current_error_message;
    }
}

// Message handling: prioritize message from GET if available (after redirect)
if (isset($_GET['message']) && !empty($_GET['message'])) {
    $message = $_GET['message']; // This comes from the redirect, already urlencoded then decoded by $_GET
} elseif (!empty($action_message)) { // If action_message was set but redirect didn't happen (e.g. header error)
    $message = $action_message;
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manage Users</title>
    <link rel="stylesheet" href="../css/style.css"> <!-- Adjust path -->
    <style>
        body { font-family: sans-serif; padding: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f0f0f0; }
        .action-links a { margin-right: 10px; }
        .action-links a.delete-link { color: #dc3545; }
        .message { padding: 10px; margin-bottom:15px; border-radius:3px; }
        .success { background-color: #d4edda; color: #155724; border:1px solid #c3e6cb; }
        .error { background-color: #f8d7da; color: #721c24; border:1px solid #f5c6cb; }
    </style>
</head>
<body>
    <h1>Manage Users</h1>
    <p><a href="dashboard.php">Back to Dashboard</a></p>

    <?php if ($message): ?>
        <div class="message <?php echo (stripos(strtolower($message), 'error') === false && stripos(strtolower($message), 'not found') === false) ? 'success' : 'error'; ?>">
            <?php echo htmlspecialchars(urldecode($message)); // urldecode because message from GET is urlencoded by us ?>
        </div>
    <?php endif; ?>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Registered At</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($users_list)): ?>
                <?php foreach ($users_list as $user_item): ?>
                    <tr>
                        <td><?php echo $user_item['id']; ?></td>
                        <td><?php echo htmlspecialchars($user_item['username']); ?></td>
                        <td><?php echo htmlspecialchars($user_item['email']); ?></td>
                        <td><?php echo $user_item['created_at']; ?></td>
                        <td class="action-links">
                            <a href="edit_user.php?id=<?php echo $user_item['id']; ?>">Edit (Not Implemented)</a>
                            <a href="manage_users.php?action=delete&id=<?php echo $user_item['id']; ?>" class="delete-link" onclick="return confirm('Are you sure you want to delete this user? This action cannot be undone and will remove related data like comments and favorites.');">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="5">No users found.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>
</body>
</html>
