<?php
session_start();
require_once '../config/config.php';

// Placeholder for admin authentication
if (!isset($_SESSION['username'])) {
    echo "<p style='color:red;'><strong>Note:</strong> Admin authentication is not yet implemented. This page should be protected.</p>";
}

$message = $_GET['message'] ?? ''; // For displaying messages from GET params
$action_message = ''; // For messages generated by actions on this page load

// Handle Delete Action
if (isset($_GET['action']) && $_GET['action'] === 'delete' && isset($_GET['id'])) {
    $anime_id_to_delete = $_GET['id'];
    try {
        $conn->beginTransaction();

        // The ON DELETE CASCADE constraints should handle related tables:
        // - anime_genres
        // - episodes (and by extension, comments linked to episodes, and watch_history)
        // - comments (directly linked to anime_id)
        // - favorites

        $stmt = $conn->prepare("DELETE FROM anime WHERE id = :id");
        $stmt->bindParam(':id', $anime_id_to_delete, PDO::PARAM_INT);
        $stmt->execute();

        if ($stmt->rowCount() > 0) {
            $conn->commit();
            $action_message = "Anime (ID: $anime_id_to_delete) and all related data deleted successfully!";
        } else {
            $conn->rollBack(); // Or commit if no rows affected is not an error in this context
            $action_message = "Error: Anime (ID: $anime_id_to_delete) not found or already deleted.";
        }
    } catch (PDOException $e) {
        if ($conn->inTransaction()) {
            $conn->rollBack();
        }
        $action_message = "Error deleting anime (ID: $anime_id_to_delete): " . $e->getMessage();
    }
    // Redirect to clean the URL and show the message
    header("Location: manage_anime.php?message=" . urlencode($action_message));
    exit;
}


// Fetch all anime for listing
$all_anime = [];
try {
    $stmt_anime = $conn->query("SELECT id, title, type, status, created_at FROM anime ORDER BY title ASC");
    if ($stmt_anime) $all_anime = $stmt_anime->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    // If $message is already set from GET, append. Otherwise, set it.
    $current_error_message = " Error fetching anime list: " . $e->getMessage();
    if(!empty($message)) {
        $message .= urldecode($current_error_message); // urldecode if message came from GET
    } else {
        $message = $current_error_message;
    }
}

// If $action_message is set (e.g. from a delete that didn't redirect due to header issues before exit), prefer it.
// Or, if message came from GET, use that.
if (!empty($action_message) && empty($_GET['message'])) { // action_message takes precedence if no GET message
    $message = $action_message;
} elseif (isset($_GET['message']) && !empty($_GET['message'])) { // Ensure GET message is prioritized if present
    $message = $_GET['message'];
}


?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manage Anime</title>
    <link rel="stylesheet" href="../css/style.css"> <!-- Adjust path -->
    <style>
        body { font-family: sans-serif; padding: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f0f0f0; }
        .action-links a { margin-right: 10px; }
        .action-links a.delete-link { color: #dc3545; }
        .message { padding: 10px; margin-bottom:15px; border-radius:3px; }
        .success { background-color: #d4edda; color: #155724; border:1px solid #c3e6cb; }
        .error { background-color: #f8d7da; color: #721c24; border:1px solid #f5c6cb; }
        .add-button { display: inline-block; padding: 10px 15px; background-color: #28a745; color: white; text-decoration: none; border-radius: 5px; margin-bottom: 15px;}
    </style>
</head>
<body>
    <h1>Manage Anime</h1>
    <p><a href="dashboard.php">Back to Dashboard</a></p>

    <?php if ($message): ?>
        <div class="message <?php echo (stripos(strtolower($message), 'error') === false && stripos(strtolower($message), 'not found') === false) ? 'success' : 'error'; ?>">
            <?php echo htmlspecialchars(urldecode($message)); // urldecode because message from GET is urlencoded ?>
        </div>
    <?php endif; ?>

    <a href="edit_anime.php?action=add" class="add-button">Add New Anime</a>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($all_anime)): ?>
                <?php foreach ($all_anime as $anime_item): ?>
                    <tr>
                        <td><?php echo $anime_item['id']; ?></td>
                        <td><?php echo htmlspecialchars($anime_item['title']); ?></td>
                        <td><?php echo htmlspecialchars($anime_item['type'] ?? 'N/A'); ?></td>
                        <td><?php echo htmlspecialchars($anime_item['status'] ?? 'N/A'); ?></td>
                        <td><?php echo $anime_item['created_at']; ?></td>
                        <td class="action-links">
                            <a href="edit_anime.php?action=edit&id=<?php echo $anime_item['id']; ?>">Edit</a>
                            <a href="manage_episodes.php?anime_id=<?php echo $anime_item['id']; ?>">Episodes</a>
                            <a href="manage_anime.php?action=delete&id=<?php echo $anime_item['id']; ?>" class="delete-link" onclick="return confirm('Are you sure you want to delete this anime and all its episodes/comments? This action cannot be undone.');">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="6">No anime found.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>
</body>
</html>
